### PR TITLE
Add more S3 / Minio test infrastructure

### PR DESCRIPTION
**Pull request by MrCreosote**
* mc to add users, apparently there's no way to do this via the client
* helper methods for creating buckets and files

This is all used locally for testing the s3 client I'm working on, but including it all at once would lead to a large, hard to read PR

### CODE REVIEW

**Review by Tianhao-Gu — APPROVED** [review]
LGTM. The current local setup makes this repo quite development-unfriendly. I hope we're not over-engineering things to the point where it becomes difficult to maintain in the future. I feel we will spend more time on unit testing than on actual development for this repo.

**Comment by MrCreosote** [comment]
> The current local setup makes this repo quite development-unfriendly. 

I'm not sure why you're saying that, it's totally simple to use. This is the setup I use for virtually every other KBase service I work on.

**Comment by Tianhao-Gu** [comment]
> > The current local setup makes this repo quite development-unfriendly.
> 
> I'm not sure why you're saying that, it's totally simple to use. This is the setup I use for virtually every other KBase service I work on.

nahhh I was just trying to express my hope that it won't become too difficult for someone to run unit tests and contribute to the codebase in case they have a hard time installing some of the executables. It reminds me of the time it took me a long while to get the sample-service test running, and I even had to use a virtual machine to run workspace tests, etc. That's what I mean by `development-unfriendly`.

**Comment by bio-boris** [comment]
I think it would be more developer friendly if instead of installing dependencies, it used docker images and used docker-compose or Kompose

**Comment by bio-boris** [comment]
Especially given that most KBase developers are using MacOS rather than linux.

**Pull request merged**
