### PR TITLE
Minio -> NERSC file transfer pt 2: file transfer method

### PR DESCRIPTION
**Pull request by MrCreosote**
PR 2/2. 1st part contains the manager class and sets up the code @ NERSC, 2nd part has the actual file transfer method added to the manager.

Prior to the manual test, `~/tmp` at Perlmutter is empty.

```python
In [8]: from authlib.oauth2.rfc7523 import PrivateKeyJWT

In [9]: from authlib.integrations.httpx_client.oauth2_client import AsyncOAuth2C
   ...: lient

In [11]: nersc_token_url = "https://oidc.nersc.gov/c2id/token"

In [12]: auth = AsyncOAuth2Client(nersc_client_id, nersc_private_key, PrivateKey
    ...: JWT(nersc_token_url), grant_type="client_credentials", token_endpoint=n
    ...: ersc_token_url)

In [13]: await auth.fetch_token();

In [14]: async def get_token():
    ...:     await auth.ensure_active_token(auth.token)
    ...:     return auth.token["access_token"]
    ...:

In [15]: from cdmtaskservice.s3.paths import S3Paths

In [16]: from cdmtaskservice.s3.client import S3Client

In [17]: from cdmtaskservice.nersc import manager

In [18]: from pathlib import Path

In [19]: from sfapi_client import AsyncClient

In [20]: paths = S3Paths([f"{root}/{f}" for f in files_procs])

In [21]: paths.paths
Out[21]:
('cdm-lake/fast-genomics-source/AllGenome_202406051229.csv',
 'cdm-lake/fast-genomics-source/ClusterProtein_202406051230.csv',
 'cdm-lake/fast-genomics-source/ClusteringInfo_202406051230.csv',
 'cdm-lake/fast-genomics-source/Gene_202406051230.csv',
 'cdm-lake/fast-genomics-source/Genome_202406051230.csv',
 'cdm-lake/fast-genomics-source/Protein_202406051230.csv',
 'cdm-lake/fast-genomics-source/Scaffold_202406051230.csv',
 'cdm-lake/fast-genomics-source/SubDb_202406051231.csv',
 'cdm-lake/fast-genomics-source/Taxon_202406051231.csv')

In [22]: s3c = await S3Client.create("http://localhost:9002", minio_access_key,
    ...: minio_secret_key)

In [23]: meta = await s3c.get_object_meta(paths, concurrency=5)

In [24]: s3c_external = await S3Client.create("https://ci.berkeley.kbase.us:9000
    ...: ", minio_access_key, minio_secret_key, skip_connection_check=True)

In [25]: urls = await s3c_external.presign_get_urls(paths)

In [26]: nerscman = await manager.NERSCManager.create(
    ...:     get_token,
    ...:     Path("/global/homes/g/gaprice/tmp/cts_test/code"),
    ...:     Path("/global/homes/g/gaprice/tmp/cts_test/jaws"),
    ...: )

In [27]: tid = await nerscman.download_s3_files("fake_job_id", meta, urls, "http
    ...: s://teletubbiesunleashed.com", insecure_ssl=True, concurrency=5)

In [29]: beta_url="https://api.nersc.gov/api/beta"

In [30]: async with AsyncClient(api_base_url=beta_url, client_id=nersc_client_id
    ...: , secret=nersc_private_key) as cli:
    ...:     ret = await cli.get("callback/")
    ...:     print(ret.json())
    ...:
[{'timeout': 259200, 'job_condition': None, 'path_condition': {'path':
'$SCRATCH/cdm_task_service/fake_job_id/download_manifest.json.complete',
'machine': 'dtns'}, 'url': 'https://teletubbiesunleashed.com', 'email':
None}]

In [31]: async with AsyncClient(client_id=nersc_client_id, secret=nersc_private_
    ...: key) as cli:
    ...:     res = await cli.get(f"tasks/{tid}")
    ...:     print(res.json())
    ...:
{'id': '686818', 'status': 'new', 'result': None}

In [32]: async with AsyncClient(client_id=nersc_client_id, secret=nersc_private_
    ...: key) as cli:
    ...:     res = await cli.get(f"tasks/{tid}")
    ...:     print(res.json())
    ...:
{'id': '686818', 'status': 'completed', 'result': '{"status": "ok",
"output": "PYTHONPATH=[/global/homes/g/gaprice/tmp/cts_test/code]\\nCTS_MANIFEST_LOCATION=[/global/pscratch/sd/g/gaprice/cdm_task_service/fake_job_id/download_manifest.json]\\nCTS_TOUCH_ON_COMPLETE=[/global/pscratch/sd/g/gaprice/cdm_task_service/fake_job_id/download_manifest.json.complete]\\nSCRATCH=[/global/pscratch/sd/g/gaprice]\\n",
"error": ""}'}
```

```
gaprice@perlmutter:login16:~/tmp> tree -h
.
└── [ 512]  cts_test
    ├── [ 512]  code
    │   ├── [ 512]  cdmtaskservice
    │   │   ├── [ 512]  nersc
    │   │   │   └── [1.4K]  remote.py
    │   │   └── [ 512]  s3
    │   │       ├── [ 512]  __pycache__
    │   │       │   └── [ 16K]  remote.cpython-311.pyc
    │   │       └── [ 11K]  remote.py
    │   └── [ 495]  process_data_transfer_manifest.sh
    └── [ 512]  jaws
        └── [ 512]  fake_job_id
            └── [ 512]  cdm-lake
                └── [4.0K]  fast-genomics-source
                    ├── [ 20M]  AllGenome_202406051229.csv
                    ├── [  45]  ClusteringInfo_202406051230.csv
                    ├── [  24]  ClusterProtein_202406051230.csv
                    ├── [2.3G]  Gene_202406051230.csv
                    ├── [1.8M]  Genome_202406051230.csv
                    ├── [3.1G]  Protein_202406051230.csv
                    ├── [ 50M]  Scaffold_202406051230.csv
                    ├── [ 25K]  SubDb_202406051231.csv
                    └── [621K]  Taxon_202406051231.csv

10 directories, 13 files
gaprice@perlmutter:login16:~/tmp>
```

### CODE REVIEW

**Review by Tianhao-Gu — APPROVED** [review]
LGTM. It's useful to document the command-line instructions so other developers can easily reference them. Perhaps at a later time, once everything is complete.

**Comment by MrCreosote** [comment]
Which command line instructions are you talking about?

**Comment by Tianhao-Gu** [comment]
> Which command line instructions are you talking about?

the ones in the very first PR conversation. 
```
from authlib.oauth2.rfc7523 import PrivateKeyJWT
... ...
```

**Comment by MrCreosote** [comment]
Oh, you mean the stuff in the ipython session? All that will be hidden behind the service API, it's not expected that anyone will ever actually try to run the code this way. This is just for testing low level code that'll be glued together later

**Comment by Tianhao-Gu** [comment]
> Oh, you mean the stuff in the ipython session? All that will be hidden behind the service API, it's not expected that anyone will ever actually try to run the code this way. This is just for testing low level code that'll be glued together later

👍

**Pull request merged**
