### PR TITLE
Vendor python-hostname

### PR DESCRIPTION
**Pull request by MrCreosote**
Will be needed for validating the docker image string hostname, if one exists

### CODE REVIEW

**Review by Tianhao-Gu — COMMENTED** [review]
no need to install `dnspython`?  I didn't review anything in `cdmtaskservice/vendored/hostname`, just copy and paste? We will be using everything in this custom package? Why not build our version with `dnspython`?

**Comment by MrCreosote** [comment]
> no need to install dnspython?

It's installed locally, it'll be in the next PR. I can push the Pipfiles up now if you want, LMK

> I didn't review anything in cdmtaskservice/vendored/hostname, just copy and paste?

Yes, other than the readme and 1 changed import line

> We will be using everything in this custom package?

I don't know. It's not many lines though so probably

> Why not build our version with dnspython?

Why spend time writing, testing, and maintaining our own code when this already exists? Someone else has already done the work, no need to duplicate effort

**Comment by MrCreosote** [comment]
Think of this as pip installing a module, except it's not on pip so we do it this way instead

**Comment by Tianhao-Gu** [comment]
> Why spend time writing, testing, and maintaining our own code when this already exists? Someone else has already done the work, no need to duplicate effort

okay, looks like this project from a random person with no folks, no starts has earned your trust

**Comment by MrCreosote** [comment]
This is literally no different to pip installing some random python package, except the code is right there for you to review. If you have concerns about it, I encourage you to review it, it's very small

If this was a python package there would be no controversy here

**Comment by Tianhao-Gu** [comment]
> This is literally no different to pip installing some random python package, except the code is right there for you to review. If you have concerns about it, I encourage you to review it, it's very small
> 
> If this was a python package there would be no controversy here

I'm okay with it since I've already approved the PR, so if you think it's good, we're all set.

**Comment by MrCreosote** [comment]
> I've already approved the PR

You did, but you also implied I was being careless. Naturally, I could not brook such a heinous and libelous allegation and felt compelled to retort. I have feelings too, you know

All that being said, if there's a python package on pypi with equivalent functionality and tons of stars and uses I'd be more than happy to switch to it. This is what I was able to find

**Comment by bio-boris** [comment]
* https://yozachar.github.io/pyvalidators/stable/api/hostname/
* https://github.com/kjd/idna
* https://github.com/ypcrts/fqdn

**Comment by MrCreosote** [comment]
Oh great. Now I'm wondering what the heck search terms I was using as fqdn is hit # 2 when I search now

**Pull request merged**
